dashboards/Disk_Performance.json, dashboards/PXC_Galera_Graphs.json
Replace HELP sections at the bottom of the dashboards with widget
descriptions.
=> Disk performance, Galera graphs: use descriptions

dashboards/MySQL_InnoDB_Metrics.json
ICP now works for all flavours of MySQL, wherever INNODB_METRICS is available and enabled:
* Percona Server
* Oracle MySQL
* MariaDB
=> Adding support for Index Condition Pushdown (ICP) PMM-724

pmm-app/src/README.md, pmm-app/src/plugin.json
https://jira.percona.com/browse/PMM-2840
We are moving  non-Dashboard pages to  separate menu  instead of using  Dashboards menu
=> PMM-2840 Add PMM to Grafana menu

pmm-app/src/pmm-update-panel/index.html, pmm-app/src/pmm-update-panel/modal.html, pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-4690
=> PMM-4690 Fix UI of pmm update.

README.md
Added the missing set of Grafana dashboards in the list provided by Percona for database and system monitoring using Prometheus datasource.
I installed on my system and found out there were more dashboards provided then Listed, thought of adding in the list.
=> PMM-5517 Add missed dashboards to README.md file

pmm-app/src/pmm-check/CheckPanel.tsx
This PR removes the size params passed from Grafana to the panel.
Not that I like it, since it's not removing the root cause, but that fixes the rendering problem for both the table and the button.
https://github.com/Percona-Lab/pmm-submodules/pull/829
=> SAAS-122 fix refresh button margins

dashboards/Prometheus.json
[![PMM-6191](https://badgen.net/badge/JIRA/PMM-6191/green)](https://jira.percona.com/browse/PMM-6191)
* Fix: count cpu metrics
CPU Count Total and Limit should be using avg; count will return the correct value, avg will return a wrong value.
* PMM-6191 Fix Prometheus Process CPU Usage formulas
Co-authored-by: Vadim Yalovets <vadim.yalovets@percona.com>
=> PMM-6191 Fix Prometheus Process CPU Usage formulas (#800)

Jenkinsfile, pmm-app/pr.codecept.js, pmm-app/tests/QAN/steps/qanActions.js, pmm-app/tests/pages/dashboardPage.js, pmm-app/tests/pages/pmmSettingsPage.js, pmm-app/tests/verifyAWSRDSMySQLInstance_test.js, pmm-app/tests/verifyInsightDashboards_test.js, pmm-app/tests/verifyMongodbDashboards_test.js, pmm-app/tests/verifyOSDashboards_test.js
[![PMM-6455](https://badgen.net/badge/JIRA/PMM-6455/green)](https://jira.percona.com/browse/PMM-6455)
This will allow monitor Dashboard related tests to be run with Nightly Run along with QAN, and Regular UI tests that are stable and not resource hungry will run on Regular FB and server Autobuild.
It also updates the chunk value to 3, because thats more practical then having one browser run ideal and not have any tests to run
Increases default timeout for PR-pipeline to 10 mins, to avoid build abort issues.
=> PMM-6455 Fixing False positives and changing tests to Nightly 

pmm-app/tests/pages/homePage.js, pmm-app/tests/upgradePMM_test.js, pmm-app/tests/verifyDBaaS_test.js
[![PMM-6707](https://badgen.net/badge/JIRA/PMM-6707/green)](https://jira.percona.com/browse/PMM-6707)
This is to avoid using 2.9 for comparison rather use Jenkins parameter to fetch Major version being tested and load locator from that.
To avoid failure for DBaaS Cluster tests, since we can't use test  data anymore.
=> PMM-6707 change the locator fetch logic for upgrade

dashboards/PostgreSQL_Instances_Overview.json
https://github.com/Percona-Lab/pmm-submodules/pull/1723
What this PR does / why we need it: Postgres Instances Overview selectors were not working properly, namely "Environment", "Node name" and "Service"
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7224
=> PMM-7224: Fix Postgres Instances Overview selectors

pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.styles.ts
What this PR does / why we need it: the sort icons on QAN are too close to the right, making it harder to click when there's the scrollbar there.
Which issue(s) this PR fixes: https://jira.percona.com/browse/PMM-7982
=> PMM-7982: increase sort icon's right position

pmm-app/src/pmm-qan/panel/QueryAnalytics.constants.ts, pmm-app/src/pmm-qan/panel/QueryAnalytics.tools.ts, pmm-app/src/pmm-qan/panel/provider/provider.tools.ts
- Use default values for filters when they are empty to prevent errors in QAN calling the API with empty values
- Remove 'All' filter from URL when another filter is selected
https://github.com/Percona-Lab/pmm-submodules/pull/1768
=> PMM-6451 Fix passing parameters between QAN and dashboards

pmm-app/.eslintrc, pmm-app/src/pmm-qan/panel/QueryAnalytics.constants.test.tsx, pmm-app/src/pmm-qan/panel/QueryAnalytics.constants.ts, pmm-app/src/pmm-qan/panel/components/Details/Example/Example.test.tsx, pmm-app/src/pmm-update/UpdatePanel.test.tsx, pmm-app/src/pmm-update/UpdatePanel.tsx, pmm-app/src/pmm-update/components/InfoBox/InfoBox.constants.ts, pmm-app/src/pmm-update/components/InfoBox/InfoBox.messages.ts, pmm-app/src/pmm-update/components/InfoBox/InfoBox.styles.ts, pmm-app/src/pmm-update/components/InfoBox/InfoBox.test.tsx, pmm-app/src/pmm-update/components/InfoBox/InfoBox.tsx, pmm-app/src/pmm-update/types.ts, pmm-app/src/shared/core/Settings.service.ts, pmm-app/src/shared/core/__mocks__/Settings.service.ts, pmm-app/src/shared/core/index.ts, pmm-app/src/shared/core/types.ts
Shows messages when check for updates is disabled
https://github.com/percona-platform/grafana/pull/207
https://github.com/Percona-Lab/pmm-submodules/pull/1939
=> PMM-8509 Disable check updates

pmm-app/src/plugin.json
It's a very small fix for the dashboard path. We have an error in the log:
```
t=2021-12-17T13:48:53+0000 lvl=info msg=Profiler logger=plugins.backend pluginId=alexanderzobnin-zabbix-datasource enabled=false
t=2021-12-17T13:48:54+0000 lvl=eror msg="Failed to load app dashboards" logger=plugins error="open /srv/grafana/plugins/pmm-app/dist/dashboards/MongoDB/MySQL_Instances_Compare.json: no such file or directory"
```
It doesn't impact user experience but it's an error anyway.
=> PMM-7 fix dashboard path

pmm-app/src/pmm-qan/panel/components/Details/Details.tsx, pmm-app/src/pmm-qan/panel/components/Details/Metrics/Metrics.test.tsx, pmm-app/src/pmm-qan/panel/components/Details/Metrics/Metrics.tsx, pmm-app/src/pmm-qan/panel/components/Details/Metrics/Metrics.types.ts
fixing the Internal server error in some cases when grouping by User Name/Database is used in QAN
https://jira.percona.com/browse/PMM-9234
=> PMM-9234-QAN-fix-isHistogramAvailable: add groupBy

pmm-app/package-lock.json, pmm-app/package.json, pmm-app/src/pmm-qan/panel/QueryAnalytics.messages.ts, pmm-app/src/pmm-qan/panel/QueryAnalytics.styles.ts, pmm-app/src/pmm-qan/panel/QueryAnalytics.tools.test.ts, pmm-app/src/pmm-qan/panel/QueryAnalytics.tools.ts, pmm-app/src/pmm-qan/panel/QueryAnalytics.tsx, pmm-app/src/pmm-qan/panel/provider/provider.tools.ts, pmm-app/src/pmm-qan/panel/provider/provider.tsx
Adds new button to QAN to copy a sharable link. The difference between this link and the one generated by grafana is the time range (check the ticket description for further information).
Notes:
- I didn't use our copy to clipboard component because that one is for text already present in the DOM;
- I didn't use grafana's own copy to clipboard button because it has a bug on the current grafana-ui version: the button doesn't rerender after the props change. That bug was is fixed in grafana 8.
https://jira.percona.com/browse/PMM-9148
=> PMM-9148 QAN share link

dashboards/Insight/Home_Dashboard.json
Add graphs to panels after upgrade Grafana to 8 version.
https://jira.percona.com/browse/PMM-9784
Before:
After:
=> PMM-9784 Add graphs to panels. Add 1 minute resresh interval to Home Dashboard.

pmm-app/src/pmm-qan/panel/provider/provider.tools.ts, pmm-app/src/pmm-qan/panel/provider/provider.tsx
https://jira.percona.com/browse/PMM-9828
PR to fix the reset of the search page in QAN. Previously, when going to the search page by the link in the navigation, default filters were installed and the key parameter search=open was overwritten, resulting in a redirect to the QAN home page.
https://user-images.githubusercontent.com/90199600/164713356-b4409167-4f0f-4301-be4e-0b7dd79cf247.mp4
=> PMM-9828-QAN-default-filters-search-redirecting: fix redirecting

dashboards/MySQL/MySQL_InnoDB_Details.json
The description contains a typo for Threshold
[PMM-10069](https://jira.percona.com/browse/PMM-10069)
Build: [SUBMODULES-2533](https://github.com/Percona-Lab/pmm-submodules/pull/2533)
=> PMM-10069 Typo in tooltip for InnoDB Random Read Ahead

CONTRIBUTING.md, pmm-app/docker-compose.yaml
https://jira.percona.com/browse/PMM-10330
As describe in the issue the plugin path is `/srv/grafana/plugins` and not `/var/lib/grafana/plugins` like specified by the contributing guideline.
So I changed it from the `CONTRIBUTING.md` and the `docker-compose.yaml`
=> PMM-10330 fix volume mapping for plugin

dashboards/MySQL/MySQL_InnoDB_Details.json
https://jira.percona.com/browse/PMM-9398
Removing the sampling for Max Log Space Used at 1s as this breaks the rendering with too many points
- https://github.com/Percona-Lab/pmm-submodules/pull/2672
=> PMM-9398 Error for InnoDB Log Buffer Usage metric dashboard

pmm-app/src/pmm-qan/panel/provider/provider.tsx
https://jira.percona.com/browse/PMM-10483
Allow refreshing time range values event if they haven't changed.
Disallowing in would prevent the trigger of the state update which in
turn wouldn't trigger grafana variables refresh and a new api call.
=> PMM-10483 Allow QAN refresh retrigger

dashboards/Insight/VictoriaMetrics.json
PMM-11298 Changed query for "CPU Busy" panel in VictoriaMetrics dashboard.
Was:
Now:
=> PMM-11298 Change query for CPU busy VictoriaMetrics dashboard

dashboards/MySQL/PXC_Galera_Cluster_Summary.json, dashboards/MySQL/PXC_Galera_Node_Summary.json, dashboards/MySQL/PXC_Galera_Nodes_Compare.json
Fix issues with empty replication latency panels (was deprecated query). Also upgraded old version of panels to new plugins version.
PXC/Galera Nodes Compare
PXC/Galera Node Summary
PXC/Galera Nodes Compare
=> PMM-11654 Updated panels type, changed queries

pmm-app/package.json, pmm-app/yarn.lock
Bump grafana to version 9.2.13.
PMM-11762
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3128
=> PMM-11762 Bump grafana version to 9.2.13

CONTRIBUTING.md
The Community Team is closing the Discord channel and for this reason I have removed the links to the channel.
=> Discord links have been removed

dashboards/MySQL/MySQL_Instances_Overview.json
PMM-11746 Changed colors from green/orange/red to blue for read/write panels:
New:
=> PMM-11746 Removed thresholds for Top InnoDB I/O reads and writes panels

pmm-app/package.json, pmm-app/yarn.lock
Bump grafana version because of CVEs.
PMM-12114
Main PR: https://github.com/percona-platform/grafana/pull/668
=> PMM-12114 Bump grafana version to 9.2.18

dashboards/MongoDB/MongoDB_Cluster_Summary.json
[PMM-12070](https://jira.percona.com/browse/PMM-12070) Change boomtable plugin to grafana table plugin for MongoDB cluster summary dashboard
FB - https://github.com/Percona-Lab/pmm-submodules/pull/3343#issuecomment-1639603106
Before - 
After -
=> PMM-12070 Table plugin - Mongo cluster summary

pmm-app/src/pmm-qan/panel/provider/provider.tsx
[PMM-12425 ](https://jira.percona.com/browse/PMM-12425) - QAN picking different date range will cause an error
Previous fixes should be tested after this fix -
[PMM-9987](https://jira.percona.com/browse/PMM-9987)
[PMM-10483](https://jira.percona.com/browse/PMM-10483)
=> PMM-12425 fix infinite loop for setting timerange

.github/workflows/build.yml, .github/workflows/setup-page.yml, pmm-app/package.json, setup-page/.gitignore
Improvements:
- Only run QAN workflow on change in QAN
- Run lint & build for change in setup page
=> PMM-7 Run unit tests for QAN & add CI for setup page

dashboards/MongoDB/MongoDB_Cluster_Summary.json
* PMM-12962 update metric name
* update title
=> PMM-12962 update metric name (#1588)

dashboards/OS/Network_Details.json
Outgoing resets and segments are transformed to negative Y. So having a min value of 2 prevents these values from being shown.
=> OS/Network_Details: Fix outgoing resets/segments not shown

dashboards/Query Analytics/pmm-qan.json
Adding an empty expression and a range parameter allows the QAN panel to be refreshed when time/timezone changes.
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3633
=> PMM-13052 Add expression & range for QAN Metrics data source

dashboards/MongoDB/MongoDB_Router_Summary.json
- https://perconadev.atlassian.net/browse/PMM-13327
**Still todo:**
- We are currently using `"title": "Overview - $service_name"`. But `$service_name` is not printed. If this is changed with `"title": "Overview - $node_name"` it works in my environment (does it cover all environments? if yes, good.)
- Should we instead keep the title as it is, and use "repeat for service name"? right now it is using "repeat for node name". Note that if we repeat by service, the dashboard prints too many things. Either one or the other needs fix, I believe. 
- Fixed name with https://github.com/percona/grafana-dashboards/pull/1626/commits/3b2f2cdca5da47bb62a463f688f2e550ff0feba0
=> PMM-13327 - New MongoDB Router Summary dashboard

dashboards/MongoDB/MongoDB_Cluster_Summary.json, dashboards/MongoDB/MongoDB_Oplog_Details.json, dashboards/MongoDB/MongoDB_ReplSet_Summary.json
[PMM-13360](https://perconadev.atlassian.net/browse/PMM-13360) - Show node is down
[PMM-13418](https://perconadev.atlassian.net/browse/PMM-13418) - Add oplog gb/hour panel
[PMM-13360]: https://perconadev.atlassian.net/browse/PMM-13360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PMM-13418]: https://perconadev.atlassian.net/browse/PMM-13418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-13360 show node down

.github/workflows/build.yml
Update upload and download actions due to v3 version being [deprecated](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).
=> PMM-7 Update upload and download github actions

pmm-app/src/pmm-qan/panel/QueryAnalytics.constants.test.tsx, pmm-app/src/pmm-qan/panel/QueryAnalytics.constants.ts
[PMM-9288](https://perconadev.atlassian.net/browse/PMM-9288)
PMM PR: https://github.com/percona/pmm/pull/3662
Percona Toolkit PR: https://github.com/percona/percona-toolkit/pull/924
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3856
[PMM-9288]: https://perconadev.atlassian.net/browse/PMM-9288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-9288 Extended profiler.

.github/workflows/build.yml, dashboards/MongoDB/MongoDB_Cluster_Summary.json, dashboards/MongoDB/MongoDB_ReplSet_Summary.json
Cherry-pick from v3
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3882
PMM-13655
=> PMM-13655 Update query to show node is down (v2)

dashboards/MongoDB/MongoDB_Cluster_Summary.json, dashboards/MongoDB/MongoDB_Instances_Overview.json, dashboards/MongoDB/MongoDB_ReplSet_Summary.json, dashboards/MongoDB/MongoDB_Router_Summary.json
Resolves following issues:
- PMM-14107 - Rename Query Execution Times Panel to Latency
- PMM-14265 - Wrong uptime displayed for mongos nodes
- PMM-14022 - PMM shows duplicated service counts in dashboard and instance alerts
- PMM-14108 - Extend connection panel with idle connections
- PMM-14106 - Add node filter for Command Operations
FB: https://github.com/Percona-Lab/pmm-submodules/pull/4033
=> MongoDB Dashboards improvements
