dashboards/MySQL_InnoDB_Metrics.json, dashboards/MySQL_Overview.json
https://jira.percona.com/browse/PMM-734
=> Adding max_over_time to History List Length, Threads_running, Threads_connected

dashboards/MySQL_Overview.json
https://jira.percona.com/browse/PMM-807
=> Fixing Connections PromQL to use max_over_time on mysql_global_status_threads_connected

dashboards/Cross_Server_Graphs.json
request: https://www.percona.com/forums/node/47505
=> fix division by zero on Memory Usage graph

.travis.yml, README.md, misc/import-dash.py
=> Add Travis CI integration

dashboards/Advanced_Data_Exploration.json, dashboards/MariaDB.json, dashboards/MySQL_Overview.json
[PMM-1270] Make MariaDB Dashboard filter out only MariaDB hosts.
[PMM-1417] Data exploration dashboard.
[PMM-1427] Expanded System Charts Graph is wrong size in MySQL Summary.
=> Upgraded dashboards

dashboards/MySQL_InnoDB_Metrics.json, dashboards/MySQL_InnoDB_Metrics_Advanced.json, dashboards/MySQL_MyRocks_Metrics.json, dashboards/MySQL_Overview.json
[PMM-1446] Updating MySQL Threads Graph
[PMM-1455] Refined Innodb Transactions Graph
[PMM-943] InnoDB AHI Usage Graph has incorrect naming and hit ratio computation
[PMM-1312] Develop dashboard and graphs for MyRocks
=> Dashboards updates

dashboards/Prometheus.json, misc/cleanup-dash.py
* Added clean up python script with common checks.
=> [PMM-1585] Include updated Prometheus dashboard

pmm-app/dist/dashboards/pmm-qan.json
To make it synced with installed PMM version where  we have 1h.
Refresh  - off because it'll refresh full page
=> changing time

pmm-app/src/pmm-qan-app-panel/module.ts
Set/read queryID and type from/to dashboard
=> [PMM-1829] Fix links

dashboards/Advanced_Data_Exploration.json, dashboards/Amazon_RDS___Aurora_MySQL__Metrics.json, dashboards/Cross_Server_Graphs.json, dashboards/Summary_Dashboard.json, dashboards/Trends_Dashboard.json
Cut trailing spaces in tags: Insight and Cloud
=> PMM-1822 fix Tags name in Dashboards

dashboards/Prometheus_Exporters_Overview.json
Remove the job - "Grafana" from collecting formulars
=> PMM-1966 Remove "Grafana" from list of exporters

dashboards/Prometheus_Exporter_Status.json
Added checking the metric mongodb_up
=> PMM-1974 mongodb_up in Exporter Status

dashboards/MySQL_Overview.json, dashboards/Summary_Dashboard.json, dashboards/System_Overview.json
Fixed CPU formula in dashboards:
- MySQL Overview
- Summary Dashboard
- System Overview
=> PMM-1976 CPU formula fix

dashboards/PXC_Galera_Cluster_Overview.json, dashboards/PXC_Galera_Graphs.json
PXC cluster not recognized correctly if a MariaDB node is present in
the list of hosts
=> PMM-1511 PXC cluster not recognized correctly

dashboards/pmm-add-instance.json, dashboards/pmm-qan.json, dashboards/pmm-settings.json, dashboards/pmm-summary.json
=> PMM-1738 Dashboards consistent linking

pmm-app/src/pmm-update-panel/modal.html, pmm-app/src/pmm-update-panel/module.ts
Update fix: https://jira.percona.com/browse/PMM-2124
=> [PMM-1859] Update message for successful upgrade

dashboards/Prometheus.json
=> PMM-2142 Wrong calculation of the "CPU Busy"

dashboards/CPU_Utilization_Details_Cores.json, dashboards/Home_Dashboard.json, dashboards/MySQL_Overview.json, dashboards/Prometheus_Exporters_Overview.json, dashboards/Summary_Dashboard.json, dashboards/System_Overview.json
=> PMM-2163 Update dashboards based on RDS metric

dashboards/Home_Dashboard.json
Also it's included the fix for PMM-2174 (extended hosts list).
=> PMM-2173  Summary Values inconsistent , PMM-2174 

pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-2179
=> [PMM-2179] Fix current displaying version

dashboards/MongoDB_Overview.json
Use mongodb_up variable for MongoDB Overview dashboard to identify if a host is MongoDB
=> PMM-1587 Use mongodb_up variable for a dashboard

pmm-app/src/pmm-update-panel/index.html, pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-2360
=> PMM-2360 Fix link for new version

pmm-app/src/pmm-qan-app-panel/module.ts, pmm-app/src/pmm-qan-settings-app-panel/module.ts, pmm-app/src/pmm-system-summary-app-panel/module.ts
https://jira.percona.com/browse/PMM-2402
=> PMM-2402 Cropped qan pages

pmm-app/src/pmm-add-instance-app-panel/module.ts, pmm-app/src/pmm-qan-app-panel/module.ts, pmm-app/src/pmm-qan-settings-app-panel/module.ts, pmm-app/src/pmm-system-summary-app-panel/module.ts
https://jira.percona.com/browse/PMM-2407
=> PMM-2407 Fix dropdown menu z-index

dashboards/MongoDB_InMemory.json
https://jira.percona.com/browse/PMM-2659
=> [PMM-2659] Cleanup Mongo_InMemory

pmm-app/headers/common.d.ts, pmm-app/src/pmm-update-panel/index.html, pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-2655
https://jira.percona.com/browse/PMM-2652
=> PMM-2655 Update panel redesign

pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-2748
=> PMM-2748 Change default value

pmm-app/src/pmm-qan-app-panel/module.ts
https://jira.percona.com/browse/PMM-2166
=> PMM-2166 Fix not found error

pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-2786
=> PMM-2786 Save link version to local storage

dashboards/NUMA_Overview.json, pmm-app/src/plugin.json
Also it's added changes requested in the ticket "PMM-2798 Filter hosts on NUMA dashboard"
=> PMM-2796 Overview NUMA Metrics should be NUMA Overview

pmm-app/src/pmm-update-panel/index.html, pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-2821
=> PMM-2821 Clean local storage

pmm-app/src/pmm-add-instance-app-panel/module.ts, pmm-app/src/pmm-qan-settings-app-panel/module.ts, pmm-app/src/pmm-system-summary-app-panel/module.ts
https://jira.percona.com/browse/PMM-2873
=> PMM-2873 Fix broken styles

pmm-app/src/pmm-qan-app-panel/module.ts, pmm-app/src/pmm-qan-settings-app-panel/module.ts, pmm-app/src/pmm-system-summary-app-panel/module.ts
https://jira.percona.com/browse/PMM-3072
=> PMM-3072 Fix firefox iframe cropping

pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-3126
=> PMM-3126 Add locale format date

pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-3088
=> PMM-3088 Fix downgrade update

dashboards/pmm-add-instance.json, dashboards/pmm-list.json, pmm-app/src/pmm-remote-instances-panel/module.ts, pmm-app/src/pmm-remote-instances-panel/plugin.json
https://jira.percona.com/browse/PMM-3062
=> PMM-3062 Add remote intances list panel

dashboards/pmm-list.json, pmm-app/src/pmm-remote-instances-panel/module.ts
https://jira.percona.com/browse/PMM-3185
=> PMM-3185 Fix cropped table and add transparent background

pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-3252
=> PMM-3252 Fix update button

dashboards/pmm-list.json, pmm-app/src/pmm-remote-instances-panel/plugin.json
https://jira.percona.com/browse/PMM-3272
FB - https://github.com/Percona-Lab/pmm-submodules/pull/132
=> PMM-3272 Rename RDS on Amazon RDS

pmm-app/src/pmm-update-panel/index.html, pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-3487
=> PMM-3487 Update warning

dashboards/MongoDB_WiredTiger.json
https://jira.percona.com/browse/PMM-1361?focusedCommentId=237299&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-237299
=> PMM-1361 MongoDB_WiredTiger additions

pmm-app/src/pmm-update-panel/index.html, pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-4445
https://jira.percona.com/browse/PMM-4446
=> PMM-4445 Update update plugin logic

pmm-app/src/pmm-update-panel/module.ts
Fix date format for update
Ware:
Become:
=> Fix date format for update

pmm-app/src/pmm-update-panel/module.ts
Change URL param `?force=true` to be JSON in body `{force: true}`
=> PMM-4446 Fix request of check update.

pmm-app/src/pmm-update-panel/index.html, pmm-app/src/pmm-update-panel/modal.html, pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-4447
=> PMM-4447 Update PMM server.

pmm-app/src/pmm-update-panel/index.html, pmm-app/src/pmm-update-panel/module.ts
https://jira.percona.com/browse/PMM-4724
FB: https://github.com/Percona-Lab/pmm-submodules/pull/485
=> PMM-4724 Add alt+click to force update.

pmm-app/src/pmm-qan-app-panel/module.ts
FB: https://github.com/Percona-Lab/pmm-submodules/pull/487
=> PMM-4749 Handle host params.

pmm-app/src/pmm-qan-app-panel/module.ts
FB: https://github.com/Percona-Lab/pmm-submodules/pull/488
=> PMM-4749 Handle cases with multiple selected items.

dashboards/Node_Summary.json, dashboards/Prometheus.json
FB: https://github.com/Percona-Lab/pmm-submodules/pull/482
=> PMM-2937 time before running out of space

dashboards/MongoDB_Instances_Overview.json, dashboards/MySQL_Instances_Overview.json, dashboards/Nodes_Overview.json, dashboards/PostgreSQL_Instances_Overview.json
server docker - perconalab/pmm-server-fb:PR-553-b3c68c8
https://github.com/Percona-Lab/pmm-submodules/pull/553
=> PMM-5037 Add graphs drilldown links to services overview dashboards

dashboards/Prometheus.json
Jira Issue
https://jira.percona.com/browse/PMM-5053
=> PMM-5053 Tooltip for Head Block for Prometheus Dashboard was added

pmm-app/src/pmm-add-instance-app-panel/AddInstance/AddInstance.test.tsx, pmm-app/src/pmm-add-instance-app-panel/AddInstance/AddRemoteInstance/AddRemoteInstance.test.tsx, pmm-app/src/pmm-add-instance-app-panel/AddInstance/AddRemoteInstance/AddRemoteInstance.tsx, pmm-app/src/pmm-add-instance-app-panel/DiscoveryPanel/DiscoveryPanel.scss, pmm-app/src/pmm-add-instance-app-panel/DiscoveryPanel/DiscoveryPanel.tsx, pmm-app/src/react-plugins-deps/components/FieldsComponents/Input/Input.tsx
https://github.com/Percona-Lab/pmm-submodules/pull/577
=> PMM-5134: rds cleanup

dashboards/MongoDB_InMemory_Details.json, dashboards/MongoDB_Instance_Summary.json, dashboards/MongoDB_MMAPv1_Details.json, dashboards/MongoDB_ReplSet_Summary.json, dashboards/MongoDB_RocksDB_Details.json, dashboards/MongoDB_WiredTiger_Details.json, dashboards/MySQL_InnoDB_Compression_Details.json, dashboards/MySQL_InnoDB_Details.json, dashboards/MySQL_Instance_Summary.json, dashboards/MySQL_MyISAM_Aria_Details.json, dashboards/MySQL_MyRocks_Details.json, dashboards/MySQL_Performance_Schema_Details.json, dashboards/MySQL_Query_Response_Time_Details.json, dashboards/MySQL_Replication_Summary.json, dashboards/MySQL_Table_Details.json, dashboards/MySQL_TokuDB_Details.json, dashboards/MySQL_User_Details.json, dashboards/MySQL_Wait_Event_Analyses_Details.json, dashboards/PostgreSQL_Instance_Summary.json
https://github.com/Percona-Lab/pmm-submodules/pull/581
server docker - perconalab/pmm-server-fb:PR-581-82d9915
=> PMM-5149 Fix the element Disk_Space for RDS instances

dashboards/MongoDB_InMemory_Details.json, dashboards/MongoDB_Instance_Summary.json, dashboards/MongoDB_MMAPv1_Details.json, dashboards/MongoDB_ReplSet_Summary.json, dashboards/MongoDB_RocksDB_Details.json, dashboards/MongoDB_WiredTiger_Details.json, dashboards/MySQL_InnoDB_Compression_Details.json, dashboards/MySQL_InnoDB_Details.json, dashboards/MySQL_Instance_Summary.json, dashboards/MySQL_MyISAM_Aria_Details.json, dashboards/MySQL_MyRocks_Details.json, dashboards/MySQL_Performance_Schema_Details.json, dashboards/MySQL_Query_Response_Time_Details.json, dashboards/MySQL_Replication_Summary.json, dashboards/MySQL_Table_Details.json, dashboards/MySQL_TokuDB_Details.json, dashboards/MySQL_User_Details.json, dashboards/MySQL_Wait_Event_Analyses_Details.json, dashboards/PostgreSQL_Instance_Summary.json
https://github.com/Percona-Lab/pmm-submodules/pull/585
=> PMM-5149 Restored fstype range

pmm-app/src/pmm-add-instance-app-panel/panel.scss, pmm-app/src/pmm-inventory/panel.scss, pmm-app/src/pmm-inventory/panel.tsx, pmm-app/src/pmm-settings/panel.scss, pmm-app/src/react-plugins-deps/style.less, pmm-app/src/react-plugins-deps/styles.scss
https://github.com/Percona-Lab/pmm-submodules/pull/589
=> PMM-5191: style leak fixed

pmm-app/src/pmm-add-instance-app-panel/panel.scss, pmm-app/src/pmm-add-instance-app-panel/panel.tsx, pmm-app/src/pmm-inventory/panel.scss, pmm-app/src/pmm-inventory/panel.tsx, pmm-app/src/pmm-settings/panel.scss, pmm-app/src/pmm-settings/panel.tsx, pmm-app/src/react-plugins-deps/components/helpers/styling.ts, pmm-app/src/react-plugins-deps/styles.scss
https://github.com/Percona-Lab/pmm-submodules/pull/592
For some mysterious reason we had a problem with panel-container styling after navigation from left grafana menu, to prevent it in the future, panel-container wrapper will be styled now with special class - custom-grafana-plugin
=> PMM-5206: dashboards styling fixed

dashboards/Prometheus.json, pmm-app/src/pmm-add-instance-app-panel/DiscoveryPanel/CredentialsForm.tsx, pmm-app/src/pmm-settings/Parts/Diagnostics/Diagnostics.tsx, pmm-app/src/pmm-settings/Parts/Diagnostics/__snapshots__/Diagnostics.test.tsx.snap
https://github.com/Percona-Lab/pmm-submodules/pull/605
=> PMM-5211: update links and texts

dashboards/Prometheus_Exporters_Overview.json
=> PMM-5238 Include and clarify rds_exporter metrics on Exporters Overview

dashboards/Prometheus_Exporter_Status.json
=> PMM-5230 fix chart rate of scrapes

pmm-app/package.json, pmm-app/src/pmm-qan-app-panel/module.ts
https://github.com/Percona-Lab/pmm-submodules/pull/588
=> PMM-5142: QAN variables update fix

README.md, misc/cleanup-dash.py, misc/export-dash.py, pmm-app/README.md
=> PMM-5104 Remove CloudWatch Grafana datasource remnants

dashboards/Network_Details.json
=> PMM-4769 wrong value for Timeout value used for retransmitting

dashboards/MySQL_InnoDB_Details.json
=> PMM-5295 Innodb Transaction Rollback Rate is not correct

dashboards/Prometheus.json
=> PMM-5340 fix graph scraping time drift

dashboards/CPU_Utilization_Details.json, dashboards/Disk_Details.json, dashboards/Memory_Details.json, dashboards/NUMA_Details.json, dashboards/Network_Details.json, dashboards/Node_Summary.json, dashboards/Nodes_Overview.json, dashboards/Processes_Details.json
=> PMM-5394 resolution fix for node dashboards

pmm-app/src/react-plugins-deps/global-styles/buttons.scss, pmm-app/src/react-plugins-deps/styles.scss
Issue after refactoring:
After fix:
=> PMM-5424: restore buttons.scss styles

dashboards/Prometheus_Exporter_Status.json
=> PMM-5430 MySQL Exporter section Collapse on Prometheus Exporter Status

dashboards/MySQL_Instance_Summary.json, dashboards/MySQL_Instances_Compare.json, dashboards/MySQL_Instances_Overview.json
=> PMM-5465 Set correct row names on MySQL dashboards

dashboards/CPU_Utilization_Details.json, dashboards/Disk_Details.json, dashboards/MongoDB_InMemory_Details.json, dashboards/MongoDB_Instance_Summary.json, dashboards/MongoDB_MMAPv1_Details.json, dashboards/MongoDB_RocksDB_Details.json, dashboards/MongoDB_WiredTiger_Details.json, dashboards/MySQL_InnoDB_Compression_Details.json, dashboards/MySQL_InnoDB_Details.json, dashboards/MySQL_Instance_Summary.json, dashboards/MySQL_MyISAM_Aria_Details.json, dashboards/MySQL_MyRocks_Details.json, dashboards/MySQL_Performance_Schema_Details.json, dashboards/MySQL_Query_Response_Time_Details.json, dashboards/MySQL_Table_Details.json, dashboards/MySQL_TokuDB_Details.json, dashboards/MySQL_User_Details.json, dashboards/MySQL_Wait_Event_Analyses_Details.json
=> PMM-5439 Add changes to dashboards for RDS instances - fix

dashboards/PostgreSQL_Instance_Summary.json, dashboards/PostgreSQL_Instances_Overview.json
=> PMM-5427 Resolution fix for PostgreSQL Dashboards

dashboards/Memory_Details.json, dashboards/NUMA_Details.json, dashboards/Node_Summary.json, dashboards/Nodes_Compare.json
=> PMM-5461 Use fixed colors for Node - Memory graph

dashboards/MySQL_Replication_Summary.json, dashboards/PXC_Galera_Cluster_Summary.json, dashboards/PXC_Galera_Node_Summary.json, dashboards/ProxySQL_Instance_Summary.json
=> PMM-5445 Resolution fix for HA Dashboards

dashboards/MongoDB_Cluster_Summary.json, dashboards/MongoDB_ReplSet_Summary.json
=> PMM-5445 Resolution fix for HA Dashboards fix

dashboards/Memory_Details.json, dashboards/MongoDB_Instance_Summary.json, dashboards/MySQL_MyRocks_Details.json, dashboards/NUMA_Details.json, dashboards/Node_Summary.json, dashboards/Nodes_Compare.json, dashboards/PostgreSQL_Instance_Summary.json
=> PMM-5489 Use a fixed color for Total graphs

pmm-app/src/pmm-qan-app-panel/module.ts
FB: https://github.com/Percona-Lab/pmm-submodules/pull/736
=> PMM-5528: plugin reload fix

dashboards/Node_Temperature_Details.json
=> PMM-5523 Chips Temprature Reports Show invalid/Wrong Temprature

dashboards/CPU_Utilization_Details.json, dashboards/MongoDB_Cluster_Summary.json, dashboards/MongoDB_Instances_Compare.json, dashboards/MongoDB_Instances_Overview.json, dashboards/MySQL_InnoDB_Compression_Details.json, dashboards/MySQL_InnoDB_Details.json, dashboards/MySQL_Instances_Overview.json, dashboards/MySQL_MyRocks_Details.json, dashboards/Nodes_Compare.json, dashboards/Nodes_Overview.json, dashboards/PXC_Galera_Cluster_Summary.json, dashboards/PostgreSQL_Instances_Compare.json, dashboards/PostgreSQL_Instances_Overview.json, dashboards/Prometheus.json, dashboards/Prometheus_Exporter_Status.json, dashboards/Prometheus_Exporters_Overview.json
=> PMM-5605 remove extra spaces in elements names on Dashboards

Jenkinsfile
Added export of Codecov's token for Jenkins pipeline.
Codecov report and e2e test are now being run in prarllel.
=> PMM-5543 added codecov token

fix-panels.py
=> PMM-5655 remove leftovers of Grafana plugins

pmm-app/package.json, pmm-app/tests/pages/adminPage.js, pmm-app/tests/pages/qanPage.js, pmm-app/tests/qan_test.js, pmm-app/tests/verifyAWSRDSMySQLInstance_test.js, pmm-app/tests/verifyMysqlDashboards_test.js, pmm-app/tests/verifyQAN_test.js
Add following QAN tests verifies:
1. Existence of filters
2. Work of button "reset all"
3. Removing added column from the list
4. Hovering over a time metric displays a tooltip with a graph
5. Hovering over a non-time metric displays a tooltip without graph
6. Metric value matches the "Per sec" value in the tooltip
=> QAN e2e tests

pmm-app/src/pmm-check/Check.service.ts, pmm-app/src/pmm-check/CheckPanel.constants.ts, pmm-app/src/pmm-check/CheckPanel.scss, pmm-app/src/pmm-check/__mocks__/Check.service.ts, pmm-app/src/pmm-check/__mocks__/stubs.ts, pmm-app/src/pmm-check/types.ts
No FB is provided, since this is all covered by tests.
=> SAAS-87 update severity level map

dashboards/MongoDB_Cluster_Summary.json, dashboards/MongoDB_ReplSet_Summary.json, dashboards/MySQL_Replication_Summary.json, dashboards/PXC_Galera_Cluster_Summary.json, dashboards/PXC_Galera_Node_Summary.json, dashboards/ProxySQL_Instance_Summary.json, misc/cleanup-dash.py
=> PMM-5821 fix links for HA dashboards

pmm-app/tests/pages/adminPage.js, pmm-app/tests/pages/dashboardPage.js, pmm-app/tests/pages/mysqlTableDetailsPage.js
After we merged this, https://github.com/percona/pmm-server-packaging/pull/129 we need this merged
=> PMM-5549 Grafana version changes, locator (#693)

.github/workflows/stale.yml
Note: this is an experiment with a purpose to see how it works. Debug mode is on, so no effect on the repo.
=> CI: housekeeping stale branches

.github/pr-badge.yml
Ann app has been added to the repo
https://github.com/apps/pull-request-badge
=> PMM-6098 add jira issue badge/link

pmm-app/tests/verifyPMMSettingsPageElements_test.js
[![PMM-6035](https://badgen.net/badge/JIRA/PMM-6035/green)](https://jira.percona.com/browse/PMM-6035)
=> PMM-6035 Adding tests for docker env variable value

pmm-app/tests/verifyPMMSettingsPageElements_test.js
[![PMM-6035](https://badgen.net/badge/JIRA/PMM-6035/green)](https://jira.percona.com/browse/PMM-6035)
=> PMM-6035 Skip for now

pmm-app/tests/verifyPMMSettingsPageElements_test.js
[![PMM-6035](https://badgen.net/badge/JIRA/PMM-6035/green)](https://jira.percona.com/browse/PMM-6035)
=> PMM-6035 Tests for verification of Env variable value

pmm-app/tests/helper/grafana_helper.js, pmm-app/tests/pages/databaseChecksPage.js, pmm-app/tests/pages/homePage.js, pmm-app/tests/permissions_test.js
[![SAAS-155](https://badgen.net/badge/JIRA/SAAS-155/green)](https://jira.percona.com/browse/SAAS-155)
1. Implemented methods with API calls for creating a user, setting a role and deleting user
2. Added tests for checking correct message when user has not access to the panel/page
=> SAAS-155 - STT Permissions UI tests

dashboards/Node_Summary.json
[![PMM-5987](https://badgen.net/badge/JIRA/PMM-5987/green)](https://jira.percona.com/browse/PMM-5987)
=> PMM-5987 fix Total value on graph Virtual Memory Utilization

dashboards/MySQL_User_Details.json
[![PMM-5920](https://badgen.net/badge/JIRA/PMM-5920/green)](https://jira.percona.com/browse/PMM-5920)
=> PMM-5920 Incorrect metric used in formula for Rows Fetched/Read

pmm-app/tests/pages/qanPage.js, pmm-app/tests/verifyQAN_test.js
[![PMM-5911](https://badgen.net/badge/JIRA/PMM-5911/green)](https://jira.percona.com/browse/PMM-5911)
=> PMM-5911 fixing locators and minor other changes

pmm-app/tests/pages/qanPage.js, pmm-app/tests/verifyQAN_test.js
[![PMM-5911](https://badgen.net/badge/JIRA/PMM-5911/green)](https://jira.percona.com/browse/PMM-5911)
=> PMM-5911 Add old QAN functions back 

pmm-app/tests/pages/pmmInventoryPage.js
[![SAAS-187](https://badgen.net/badge/JIRA/SAAS-187/green)](https://jira.percona.com/browse/SAAS-187)
=> SAAS-187 Fix for Upgrade tests

pmm-app/tests/pages/pmmInventoryPage.js
=> PMM-6140 Fixing UI tests

pmm-app/tests/pages/pmmInventoryPage.js
=> PMM-6140 Fixing issue with rdsmysql test

pmm-app/pr.codecept.js, pmm-app/tests/pages/pmmInventoryPage.js
=> PMM-6140 fix for RDS

pmm-app/pr.codecept.js, pmm-app/tests/pages/adminPage.js, pmm-app/tests/pages/pmmInventoryPage.js, pmm-app/tests/verifyOSDashboards_test.js, pmm-app/tests/verifyPostgresqlDashboards_test.js
=> PMM-6140 Fixing Failing Test and change resolution

pmm-app/package.json, pmm-app/pr.codecept.js, pmm-app/tests/helper/codeceptjs-influxdbhelper.js, pmm-app/tests/pages/remoteInstancesPage.js
[![PMM-2](https://badgen.net/badge/JIRA/PMM-2/green)](https://jira.percona.com/browse/PMM-2)
=> Update changes from PMM-2.0

pmm-app/tests/pages/qanPage.js, pmm-app/tests/verifyQAN_test.js
=> PMM-6140 Adding QAN tests, react QAN

pmm-app/tests/pages/qanPage.js, pmm-app/tests/verifyQAN_test.js
=> PMM-6140 Fixing Failing QAN tests

pmm-app/tests/pages/qanPage.js, pmm-app/tests/verifyQAN_test.js
=> PMM-6140 Fixing PMM-T233 with invalid value failure

dashboards/MongoDB_Instances_Compare.json, dashboards/MongoDB_Instances_Overview.json, dashboards/MySQL_InnoDB_Details.json, dashboards/MySQL_Instances_Compare.json, dashboards/PostgreSQL_Instances_Overview.json, dashboards/Processes_Details.json
[![PMM-6084](https://badgen.net/badge/JIRA/PMM-6084/green)](https://jira.percona.com/browse/PMM-6084)
=> PMM-6084 Enable Match any parameter for PMM annotations

pmm-app/tests/pages/pmmSettingsPage.js
=> PMM-6140 Fixing Failing test

pmm-app/tests/upgradePMM_test.js
[![PMM-6109](https://badgen.net/badge/JIRA/PMM-6109/green)](https://jira.percona.com/browse/PMM-6109)
=> PMM-6109 Temp fix for failure

pmm-app/tests/upgradePMM_test.js
[![PMM-6109](https://badgen.net/badge/JIRA/PMM-6109/green)](https://jira.percona.com/browse/PMM-6109)
=> PMM-6109 Minor fix to whats new link test

pmm-app/tests/helper/grafana_helper.js, pmm-app/tests/verifyPMMSettingsPageElements_test.js
[![SAAS-187](https://badgen.net/badge/JIRA/SAAS-187/green)](https://jira.percona.com/browse/SAAS-187)
This allows us to set Severity directly from Test Title
=> SAAS-187 Adding allure severity support via hook

pmm-app/src/pmm-qan/panel/components/Overview/Overview.hooks.ts, pmm-app/src/pmm-qan/panel/components/Overview/Overview.tsx, pmm-app/src/pmm-qan/panel/components/Overview/components/DefaultColumns/DefaultColumns.styles.ts, pmm-app/src/pmm-qan/panel/components/Overview/components/DefaultColumns/DefaultColumns.tsx, pmm-app/src/pmm-qan/panel/components/Overview/components/MetricColumns/MetricColumns.scss, pmm-app/src/pmm-qan/panel/components/Overview/components/MetricColumns/MetricColumns.tsx, pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.styles.ts, pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.tsx, pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.types.ts, pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/index.ts, pmm-app/src/pmm-qan/panel/provider/provider.tsx
[![PMM-6139](https://badgen.net/badge/JIRA/PMM-6139/green)](https://jira.percona.com/browse/PMM-6139)
=> PMM-6139: replace table

dashboards/Advanced_Data_Exploration.json
[![PMM-6194](https://badgen.net/badge/JIRA/PMM-6194/green)](https://jira.percona.com/browse/PMM-6194)
=> PMM-6194 Set uid for Advanced Data Exploration dashboard

pmm-app/tests/pages/dashboardPage.js, pmm-app/tests/verifyMysqlDashboards_test.js
[![PMM-6245](https://badgen.net/badge/JIRA/PMM-6245/green)](https://jira.percona.com/browse/PMM-6245)
=> PMM-6245 Fix tests

dashboards/Home_Dashboard.json, dashboards/Node_Temperature_Details.json
[![PMM-6227](https://badgen.net/badge/JIRA/PMM-6227/green)](https://jira.percona.com/browse/PMM-6227)
=> PMM-6227 Node Summary Redirection from Home Dashboard does not work

pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.styles.ts, pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.tsx
[![PMM-6300](https://badgen.net/badge/JIRA/PMM-6300/green)](https://jira.percona.com/browse/PMM-6300)
=> PMM-6300 improve sorting buttons interaction

pmm-app/src/shared/components/Elements/Charts/Sparkline/Sparkline.scss
[![PMM-6329](https://badgen.net/badge/JIRA/PMM-6329/green)](https://jira.percona.com/browse/PMM-6329)
=> PMM-6329 fix sparkline tooltip visibility

pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.tsx
[![PMM-6247](https://badgen.net/badge/JIRA/PMM-6247/green)](https://jira.percona.com/browse/PMM-6247)
By mistake I removed import of this hook and it disabled original task solution, just adding hook back
=> PMM-6247 hotfix

pmm-app/tests/QAN/overview_test.js, pmm-app/tests/QAN/timerange_test.js
[![PMM-5740](https://badgen.net/badge/JIRA/PMM-5740/green)](https://jira.percona.com/browse/PMM-5740)
=> PMM-5740 unskip the failing tests

pmm-app/src/shared/components/Elements/Overlay/Overlay.styles.ts, pmm-app/src/shared/components/Elements/Overlay/Overlay.test.tsx, pmm-app/src/shared/components/Elements/Overlay/Overlay.tsx, pmm-app/src/shared/components/Elements/Overlay/Overlay.types.ts
[![PMM-6365](https://badgen.net/badge/JIRA/PMM-6365/green)](https://jira.percona.com/browse/PMM-6365)
Adds Overlay component to ensure consistent loading. There's no feature build (FB) for this PR since it only implements the component and doesn't use it. Check the PR: https://github.com/percona/grafana-dashboards/pull/893 for FB with usage of this component.
=> PMM-6365 Add overlay component

dashboards/Home_Dashboard.json, pmm-app/pr.codecept.js, pmm-app/src/pmm-update/UpdatePanel.tsx, pmm-app/tests/QAN/overview_test.js, pmm-app/tests/QAN/timerange_test.js
[![PMM-6420](https://badgen.net/badge/JIRA/PMM-6420/green)](https://jira.percona.com/browse/PMM-6420)
https://github.com/Percona-Lab/pmm-submodules/pull/998
=> PMM 6420 fix wrong version after update

pmm-app/tests/pages/api/addInstanceAPI.js, pmm-app/tests/pages/api/inventoryAPI.js, pmm-app/tests/pages/homePage.js, pmm-app/tests/pages/pmmDemoPage.js, pmm-app/tests/upgradePMM_test.js
[![PMM-5740](https://badgen.net/badge/JIRA/PMM-5740/green)](https://jira.percona.com/browse/PMM-5740)
=> PMM-5740 fix pmmdemo, skip regex in upgrade tests

pmm-app/pr.codecept.js, pmm-app/tests/pages/dashboardPage.js, pmm-app/tests/pages/pmmInventoryPage.js, pmm-app/tests/pages/pmmSettingsPage.js, pmm-app/tests/verifyOSDashboards_test.js, pmm-app/tests/verifyPMMSettingsPageElements_test.js
[![PMM-5740](https://badgen.net/badge/JIRA/PMM-5740/green)](https://jira.percona.com/browse/PMM-5740)
This is just one batch to reduce number of failed tests on FB's and autobuild jobs, continue working on fixing other issues, the Instances being used for running the tests are slower causing timeouts and errors on dashboards, adding some waits to handle false positives.
=> PMM-5740 Fixing False Positives

pmm-app/pr.codecept.js, pmm-app/tests/verifyInsightDashboards_test.js, pmm-app/tests/verifyOSDashboards_test.js, pmm-app/tests/verifyPMMSettingsPageElements_test.js
[![PMM-5740](https://badgen.net/badge/JIRA/PMM-5740/green)](https://jira.percona.com/browse/PMM-5740)
This is to reduce false positives, we will create another ticket to look into the failed tests, to make builds stable skipping them for now.
=> PMM-5740 Disable unstable tests 

Jenkinsfile, pmm-app/tests/verifyInsightDashboards_test.js, pmm-app/tests/verifyOSDashboards_test.js
[![PMM-6455](https://badgen.net/badge/JIRA/PMM-6455/green)](https://jira.percona.com/browse/PMM-6455)
…urces
=> PMM-6455 Moving unstable tests to Nightly Job with more wait & resources

pmm-app/tests/databaseChecks_test.js
[![PMM-6458](https://badgen.net/badge/JIRA/PMM-6458/green)](https://jira.percona.com/browse/PMM-6458)
=> PMM-6458 fix for broken UI test

pmm-app/tests/upgradePMM_test.js, pmm-app/tests/verifyMysqlDashboards_test.js
[![PMM-6458](https://badgen.net/badge/JIRA/PMM-6458/green)](https://jira.percona.com/browse/PMM-6458)
=> PMM-6458 Fix Upgrade pmm-settings tests, unskip

pmm-app/package-lock.json, pmm-app/package.json, pmm-app/src/pmm-qan/panel/QueryAnalytics.styles.ts, pmm-app/src/pmm-qan/panel/QueryAnalytics.tsx, pmm-app/src/pmm-qan/panel/components/Details/Details.styles.ts, pmm-app/src/pmm-qan/panel/components/Details/Details.tsx, pmm-app/src/pmm-qan/panel/components/Filters/Filters.styles.ts, pmm-app/src/pmm-qan/panel/components/Filters/Filters.test.tsx, pmm-app/src/pmm-qan/panel/components/Filters/Filters.tsx, pmm-app/src/pmm-qan/panel/components/Overview/Overview.constants.ts, pmm-app/src/pmm-qan/panel/components/Overview/components/DefaultColumns/DefaultColumns.tsx, pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.constants.ts, pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.styles.ts, pmm-app/src/pmm-qan/panel/components/Overview/components/QanTable/Table.tsx, pmm-app/src/pmm-qan/panel/provider/provider.tsx, pmm-app/src/shared/components/Elements/Scrollbar/Scrollbar.styles.tsx, pmm-app/src/shared/components/Elements/Scrollbar/Scrollbar.tsx, pmm-app/src/shared/styles.scss
[![PMM-6316](https://badgen.net/badge/JIRA/PMM-6316/green)](https://jira.percona.com/browse/PMM-6316)
https://github.com/Percona-Lab/pmm-submodules/pull/1046
=> PMM-6316 replace native scrollbars with custom

pmm-app/src/pmm-qan/panel/QueryAnalytics.styles.ts, pmm-app/src/pmm-qan/panel/QueryAnalytics.tsx, pmm-app/src/pmm-qan/panel/components/Details/Details.styles.ts, pmm-app/src/pmm-qan/panel/components/Details/Details.tsx
[![PMM-6569](https://badgen.net/badge/JIRA/PMM-6569/green)](https://jira.percona.com/browse/PMM-6569)
=> PMM-6569 fix details scrolling

pmm-app/tests/QAN/details_test.js
[![PMM-6548](https://badgen.net/badge/JIRA/PMM-6548/green)](https://jira.percona.com/browse/PMM-6548)
This avoids the infinite wait causing the test to abort with a timeout, this move to is not needed anymore
=> PMM-6548 remove the unwanted

pmm-app/pr-local.codecept.js, pmm-app/pr.codecept.js, pmm-app/tests/QAN/common_test.js, pmm-app/tests/QAN/details_test.js, pmm-app/tests/QAN/overview_test.js, pmm-app/tests/QAN/pages/qanFiltersFragment.js, pmm-app/tests/QAN/pages/qanOverviewFragment.js, pmm-app/tests/QAN/steps/qanActions.js
[![SAAS-296](https://badgen.net/badge/JIRA/SAAS-296/green)](https://jira.percona.com/browse/SAAS-296)
=> SAAS-296 overview fragment

pmm-app/tests/pages/dashboardPage.js, pmm-app/tests/upgradePMM_test.js, pmm-app/tests/verifyMysqlDashboards_test.js, pmm-app/tests/verifyOSDashboards_test.js
[![PMM-6493](https://badgen.net/badge/JIRA/PMM-6493/green)](https://jira.percona.com/browse/PMM-6493)
=> PMM-6493 Fixing Annotation tests, adding PT Summary

pmm-app/tests/pages/dashboardPage.js, pmm-app/tests/upgradePMM_test.js, pmm-app/tests/verifyMysqlDashboards_test.js, pmm-app/tests/verifyOSDashboards_test.js
[![PMM-6493](https://badgen.net/badge/JIRA/PMM-6493/green)](https://jira.percona.com/browse/PMM-6493)
=> PMM-6493 Fix for Annotation tests, PT summary tests and settings tab

pmm-app/src/pmm-qan/panel/provider/provider.tsx, pmm-app/tests/QAN/common_test.js, pmm-app/tests/QAN/overview_test.js, pmm-app/tests/QAN/pages/qanFiltersFragment.js, pmm-app/tests/QAN/pages/qanOverviewFragment.js, pmm-app/tests/QAN/steps/qanActions.js
[![PMM-6616](https://badgen.net/badge/JIRA/PMM-6616/green)](https://jira.percona.com/browse/PMM-6616)
=> PMM-6616 fix timerange issues

dashboards/MySQL_Group_Replication_Summary.json
[![PMM-6437](https://badgen.net/badge/JIRA/PMM-6437/green)](https://jira.percona.com/browse/PMM-6437)
=> PMM-6437 Group replication status and performance table

pmm-app/tests/verifyMysqlDashboards_test.js
[![PMM-6624](https://badgen.net/badge/JIRA/PMM-6624/green)](https://jira.percona.com/browse/PMM-6624)
=> PMM-6624 Fixing Filter Name

pmm-app/pr.codecept.js, pmm-app/tests/QAN/filters_test.js, pmm-app/tests/QAN/overview_test.js, pmm-app/tests/pages/dashboardPage.js
[![PMM-6624](https://badgen.net/badge/JIRA/PMM-6624/green)](https://jira.percona.com/browse/PMM-6624)
=> PMM-6624 Fixing failure for PS Filter with default version

dashboards/MySQL_Instance_Summary.json, dashboards/MySQL_Instances_Compare.json
[![PMM-6609](https://badgen.net/badge/JIRA/PMM-6609/green)](https://jira.percona.com/browse/PMM-6609)
=> PMM-6609 Modify MySQL Internal Memory Overview element

misc/cleanup-dash.py
[![PMM-6618](https://badgen.net/badge/JIRA/PMM-6618/green)](https://jira.percona.com/browse/PMM-6618)
=> PMM-6618 Modify clean_up script refer annotations

pmm-app/tests/pages/pmmInventoryPage.js, pmm-app/tests/verifyPMMInventory_test.js
[![PMM-6624](https://badgen.net/badge/JIRA/PMM-6624/green)](https://jira.percona.com/browse/PMM-6624)
=> PMM-6624 fixing UI tests 2 clients hosts delete agent tests

dashboards/CPU_Utilization_Details.json, dashboards/Memory_Details.json, dashboards/MongoDB_Cluster_Summary.json, dashboards/MongoDB_InMemory_Details.json, dashboards/MongoDB_Instance_Summary.json, dashboards/MongoDB_MMAPv1_Details.json, dashboards/MongoDB_WiredTiger_Details.json, dashboards/MySQL_Command_Handler_Counters_Compare.json, dashboards/MySQL_InnoDB_Details.json, dashboards/MySQL_MyISAM_Aria_Details.json, dashboards/MySQL_MyRocks_Details.json, dashboards/MySQL_Replication_Summary.json, dashboards/MySQL_TokuDB_Details.json, dashboards/NUMA_Details.json, dashboards/Node_Summary.json, dashboards/Nodes_Compare.json, dashboards/PXC_Galera_Cluster_Summary.json, dashboards/PXC_Galera_Node_Summary.json, dashboards/PXC_Galera_Nodes_Compare.json, dashboards/PostgreSQL_Instance_Summary.json, dashboards/PostgreSQL_Instances_Compare.json, dashboards/Prometheus.json, dashboards/Prometheus_Exporter_Status.json, dashboards/ProxySQL_Instance_Summary.json
[![PMM-6625](https://badgen.net/badge/JIRA/PMM-6625/green)](https://jira.percona.com/browse/PMM-6625)
=> PMM-6625 Set charts sorting by avg descending

pmm-app/tests/pages/dashboardPage.js, pmm-app/tests/verifyMysqlDashboards_test.js
[![PMM-6582](https://badgen.net/badge/JIRA/PMM-6582/green)](https://jira.percona.com/browse/PMM-6582)
=> PMM-6582 Group Replication Dashboard UI test

pmm-app/src/pmm-settings/components/PlatformLogin/PlatformLogin.tsx
[![PMM-6702](https://badgen.net/badge/JIRA/PMM-6702/green)](https://jira.percona.com/browse/PMM-6702)
https://github.com/Percona-Lab/pmm-submodules/pull/1139
=> PMM-6702 Dont show as logged in when email is empty

pmm-app/src/pmm-qan/panel/components/Filters/components/CheckboxGroup/CheckboxGroup.tsx
[![PMM-6764](https://badgen.net/badge/JIRA/PMM-6764/green)](https://jira.percona.com/browse/PMM-6764)
=> PMM-6764 filtering fix

dashboards/MongoDB_Instance_Summary.json
[![PMM-6736](https://badgen.net/badge/JIRA/PMM-6736/green)](https://jira.percona.com/browse/PMM-6736)
=> PMM-6736 Bind ReplSet statuses to specific colors

dashboards/Node_Summary.json, dashboards/Nodes_Overview.json
[![PMM-6730](https://badgen.net/badge/JIRA/PMM-6730/green)](https://jira.percona.com/browse/PMM-6730)
=> PMM-6730 Fix showing twice service type on DB Service Connections

pmm-app/package-lock.json, pmm-app/package.json, pmm-app/src/pmm-dbaas/DBaaS.messages.ts, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/AddXtraDBModal.test.tsx, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/AddXtraDBModal.tsx, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/AddXtraDBModal.types.ts, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/XtraDBAdvancedOptions/XtraDBAdvancedOptions.constants.ts, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/XtraDBAdvancedOptions/XtraDBAdvancedOptions.styles.ts, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/XtraDBAdvancedOptions/XtraDBAdvancedOptions.test.tsx, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/XtraDBAdvancedOptions/XtraDBAdvancedOptions.tsx, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/XtraDBAdvancedOptions/XtraDBAdvancedOptions.types.ts, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/XtraDBClusterBasicOptions/XtraDBClusterBasicOptions.test.tsx, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/XtraDBClusterBasicOptions/XtraDBClusterBasicOptions.tsx, pmm-app/src/pmm-dbaas/components/XtraDB/AddXtraDBModal/XtraDBClusterBasicOptions/XtraDBClusterBasicOptions.types.ts, pmm-app/src/pmm-dbaas/components/XtraDB/XtraDB.service.ts, pmm-app/src/pmm-dbaas/components/XtraDB/XtraDB.types.ts, pmm-app/src/pmm-dbaas/components/XtraDB/__mocks__/xtraDBClustersStubs.ts, pmm-app/src/pmm-qan/panel/components/Filters/components/CheckboxGroup/CheckboxGroup.tsx, pmm-app/src/shared/components/Form/FieldAdapters/FieldAdapters.tsx, pmm-app/src/shared/components/Form/Radio/RadioButtonGroup.tsx, pmm-app/src/shared/components/helpers/validators.test.tsx, pmm-app/src/shared/components/helpers/validators.ts, pmm-app/tests/pages/homePage.js, pmm-app/tests/upgradePMM_test.js, pmm-app/tests/verifyDBaaS_test.js
[![PMM-5993](https://badgen.net/badge/JIRA/PMM-5993/green)](https://jira.percona.com/browse/PMM-5993)
Adds DBaaS advanced options: topology, cluster size, memory and CPU resources both for PMM-5992 and PMM-5993.
https://github.com/Percona-Lab/pmm-submodules/pull/1186
=> PMM-5993 DBaaS advanced options

pmm-app/src/pmm-qan/panel/components/Details/Explain/Explain.tsx, pmm-app/tests/pages/homePage.js, pmm-app/tests/upgradePMM_test.js, pmm-app/tests/verifyDBaaS_test.js
[![PMM-6664](https://badgen.net/badge/JIRA/PMM-6664/green)](https://jira.percona.com/browse/PMM-6664)
https://github.com/Percona-Lab/pmm-submodules/pull/1194
=> PMM-6664 add explain scrollbar

pmm-app/package-lock.json, pmm-app/package.json, pmm-app/src/pmm-qan/panel/components/Filters/Filters.tools.ts, pmm-app/src/pmm-qan/panel/components/Filters/components/CheckboxGroup/CheckboxGroup.tsx, pmm-app/src/shared/components/Elements/Scrollbar/Scrollbar.tsx, pmm-app/tests/pages/homePage.js, pmm-app/tests/upgradePMM_test.js, pmm-app/tests/verifyDBaaS_test.js
[![PMM-6686](https://badgen.net/badge/JIRA/PMM-6686/green)](https://jira.percona.com/browse/PMM-6686)
=> PMM-6686 avoid calling Array.prototype.flat() to please Edge

pmm-app/tests/QAN/filters_test.js
[![PMM-6708](https://badgen.net/badge/JIRA/PMM-6708/green)](https://jira.percona.com/browse/PMM-6708)
=> PMM-6708 Fix QAN Navigation tests in PR Pipeline

pmm-app/tests/pages/dbaasPage.js, pmm-app/tests/pages/pmmDemoPage.js
[![PMM-6817](https://badgen.net/badge/JIRA/PMM-6817/green)](https://jira.percona.com/browse/PMM-6817)
=> PMM-6817 Fix UI tests (#1023)

pmm-app/pr.codecept.js, pmm-app/src/pmm-add-instance/components/AddInstance/AddInstance.test.tsx, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/AddRemoteInstance.tsx, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/AddRemoteInstance.types.ts, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.constants.ts, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.messages.ts, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.tsx, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/AdditionalOptions/AdditionalOptions.types.ts, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/FormParts.messages.ts, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/FormParts.styles.tsx, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/FormParts.test.tsx, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/FormParts.types.ts, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/Labels/Labels.tsx, pmm-app/src/pmm-add-instance/components/AddRemoteInstance/FormParts/MainDetails/MainDetails.tsx, pmm-app/src/pmm-add-instance/components/Discovery/components/Credentials/Credentials.tsx, pmm-app/src/pmm-add-instance/panel.tsx, pmm-app/tests/pages/remoteInstancesPage.js, pmm-app/tests/verifyRemoteInstances_test.js
[![PMM-5020](https://badgen.net/badge/JIRA/PMM-5020/green)](https://jira.percona.com/browse/PMM-5020)
=> PMM-5020 add tablestat

pmm-app/tests/pages/remoteInstancesPage.js
=> Fix for RDS tests

pmm-app/tests/pages/pmmSettingsPage.js, pmm-app/tests/verifyPMMSettingsPageFunctionality_test.js
[![PMM-6812](https://badgen.net/badge/JIRA/PMM-6812/green)](https://jira.percona.com/browse/PMM-6812)
=> PMM-6812 Adding back alert rules test

pmm-app/tests/pages/pmmSettingsPage.js, pmm-app/tests/verifyPMMSettingsPageFunctionality_test.js
[![PMM-6812](https://badgen.net/badge/JIRA/PMM-6812/green)](https://jira.percona.com/browse/PMM-6812)
=> PMM-6812 Adding back alert Rule tests (#1045)

pmm-app/src/pmm-dbaas/DBaaS.messages.ts, pmm-app/src/pmm-dbaas/components/DBCluster/ColumnRenderers/ColumnRenderers.tsx, pmm-app/src/pmm-dbaas/components/DBCluster/DBCluster.test.tsx, pmm-app/src/pmm-dbaas/components/DBCluster/DBCluster.tsx, pmm-app/src/pmm-dbaas/components/DBCluster/DBClusterParameters/DBClusterParameters.styles.ts, pmm-app/src/pmm-dbaas/components/DBCluster/DBClusterParameters/DBClusterParameters.test.tsx, pmm-app/src/pmm-dbaas/components/DBCluster/DBClusterParameters/DBClusterParameters.tsx, pmm-app/src/pmm-dbaas/components/DBCluster/DBClusterParameters/DBClusterParameters.types.ts, pmm-app/src/pmm-dbaas/components/DBCluster/__mocks__/dbClustersStubs.ts
[![PMM-6857](https://badgen.net/badge/JIRA/PMM-6857/green)](https://jira.percona.com/browse/PMM-6857)
=> PMM-6857 add connection details column

pmm-app/src/pmm-settings/Settings.service.ts
[![PMM-6861](https://badgen.net/badge/JIRA/PMM-6861/green)](https://jira.percona.com/browse/PMM-6861)
public_address -> pmm_public_address
=> PMM-6861 fix field name

pmm-app/tests/pages/homePage.js
[![SAAS-456](https://badgen.net/badge/JIRA/SAAS-456/green)](https://jira.percona.com/browse/SAAS-456)
=> SAAS-456 upgrade logs milestones

dashboards/MongoDB_Cluster_Summary.json
[![PMM-6952](https://badgen.net/badge/JIRA/PMM-6952/green)](https://jira.percona.com/browse/PMM-6952)
=> PMM-6952 Monitoring more than one mongos instance breaks dashboard

dashboards/ProxySQL_Instance_Summary.json
[![PMM-7054](https://badgen.net/badge/JIRA/PMM-7054/green)](https://jira.percona.com/browse/PMM-7054)
=> PMM-7054 ProxySQL Instance Summary - no Node Metrics

pmm-app/src/pmm-dbaas/components/DBCluster/DBCluster.tsx, pmm-app/src/pmm-dbaas/components/DBCluster/DBClusterName/DBClusterName.constants.ts, pmm-app/src/pmm-dbaas/components/DBCluster/DBClusterName/DBClusterName.tsx, pmm-app/src/pmm-settings/Settings.tsx, pmm-app/src/pmm-settings/components/Advanced/Advanced.test.tsx, pmm-app/src/pmm-settings/components/Advanced/Advanced.tsx
[![PMM-7032](https://badgen.net/badge/JIRA/PMM-7032/green)](https://jira.percona.com/browse/PMM-7032)
=> PMM-7032 fix cluster variable value

dashboards/MongoDB_Instance_Summary.json
[![PMM-7146](https://badgen.net/badge/JIRA/PMM-7146/green)](https://jira.percona.com/browse/PMM-7146)
=> PMM-7146 Fix ReplSet element on MongoDB dashboard

pmm-app/src/pmm-dbaas/components/DBCluster/DBClusterStatus/DBClusterStatus.styles.ts, pmm-app/src/pmm-dbaas/components/DBCluster/DBClusterStatus/DBClusterStatus.test.tsx, pmm-app/src/pmm-dbaas/components/DBCluster/DBClusterStatus/DBClusterStatus.tsx, pmm-app/tests/pages/homePage.js
[![PMM-7084](https://badgen.net/badge/JIRA/PMM-7084/green)](https://jira.percona.com/browse/PMM-7084)
=> PMM-7084 db cluster status error message icon

pmm-app/tests/pages/pmmSettingsPage.js, pmm-app/tests/verifyPMMSettingsPageFunctionality_test.js
[![PMM-6967](https://badgen.net/badge/JIRA/PMM-6967/green)](https://jira.percona.com/browse/PMM-6967)
=> PMM-6967 Fix Test with UI check and API response way

pmm-app/src/pmm-dbaas/components/Kubernetes/OperatorStatusItem/KubernetesOperatorStatus/KubernetesOperatorStatus.constants.ts
[![PMM-7221](https://badgen.net/badge/JIRA/PMM-7221/green)](https://jira.percona.com/browse/PMM-7221)
=> PMM-7221 change operator install links

dashboards/MySQL_InnoDB_Details.json
[![PMM-7213](https://badgen.net/badge/JIRA/PMM-7213/green)](https://jira.percona.com/browse/PMM-7213) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PMM-7213 remove colorizing for Data Buffer Pool Fit element

pmm-app/src/pmm-settings/Settings.messages.ts, pmm-app/src/pmm-settings/components/Communication/Communication.messages.ts
[![PMM-7249](https://badgen.net/badge/JIRA/PMM-7249/green)](https://jira.percona.com/browse/PMM-7249) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://github.com/Percona-Lab/pmm-submodules/pull/1365
=> PMM-7249 Fix IA doc links

dashboards/Nodes_Overview.json
[![PMM-7129](https://badgen.net/badge/JIRA/PMM-7129/green)](https://jira.percona.com/browse/PMM-7129) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PMM-7129 CPU usage data on nodes overview contradicts itself

pmm-app/tests/pages/homePage.js, pmm-app/tests/pages/pmmInventoryPage.js, pmm-app/tests/verifyPMMInventory_test.js, pmm-app/tests/verifyPMMSettingsPageElements_test.js
[![PMM-7187](https://badgen.net/badge/JIRA/PMM-7187/green)](https://jira.percona.com/browse/PMM-7187) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PMM-7187 Tests for Inventory Page to check Agent Status

dashboards/ProxySQL_Instance_Summary.json, pmm-app/pr-local.codecept.js, pmm-app/pr.codecept.js, pmm-app/tests/ia/alertRules_test.js, pmm-app/tests/ia/pages/alertRulesPage.js, pmm-app/tests/ia/pages/api/channelsAPI.js, pmm-app/tests/ia/pages/api/rulesAPI.js, pmm-app/tests/ia/pages/api/templatesAPI.js, pmm-app/tests/ia/templates/templateForRules.yaml
[![PMM-7320](https://badgen.net/badge/JIRA/PMM-7320/green)](https://jira.percona.com/browse/PMM-7320) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> PMM-7320 Alert rules UI tests

pmm-app/src/pmm-dbaas/components/DBCluster/DBCluster.hooks.ts
[![PMM-7323](https://badgen.net/badge/JIRA/PMM-7323/green)](https://jira.percona.com/browse/PMM-7323) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://github.com/Percona-Lab/pmm-submodules/pull/1406
=> PMM-7323 Remove cluster from right kubernetes

.github/workflows/stale.yml, .gitignore
Need this for two reasons:
- to test how it works on this repo
- to automate the process
Note: scheduled workflows can only be committed to the base branch
=> ci: add stale.yml to workflows

dashboards/PostgreSQL_Instance_Summary.json
=> PMM-7416 use db variable in formulas

dashboards/MySQL_Replication_Summary.json
=> PMM-6636 Binlog Size not being graph when the instance is a MySQL RDS

pmm-app/tests/QAN/common_test.js, pmm-app/tests/QAN/details_test.js, pmm-app/tests/QAN/filters_test.js, pmm-app/tests/verifyAWSRDSMySQLInstance_test.js, pmm-app/tests/verifyInsightDashboards_test.js, pmm-app/tests/verifyMysqlDashboards_test.js, pmm-app/tests/verifyPMMSettingsPageFunctionality_test.js
Reverts percona/grafana-dashboards#1130
=> Revert "Nightly-job"

pmm-app/tests/pages/dashboardPage.js
hotfix to handle failure on pt-mysql-summary verification
=> Fix the locator for updated Grafana

pmm-app/tests/DbaaS/verifyDBaaS_test.js
https://github.com/percona-platform/grafana/pull/66/
https://github.com/Percona-Lab/pmm-submodules/pull/1528/files
=> PMM-7193 Fix e2e tests after parsing DBaaS number of nodes

pmm-app/codeceptConfigHelper.js, pmm-app/package-lock.json, pmm-app/package.json, pmm-app/pr-local.codecept.js, pmm-app/pr.codecept.js, pmm-app/tests/ia/alerts_test.js, pmm-app/tests/ia/pages/api/alertsAPI.js, pmm-app/tests/ia/pages/api/channelsAPI.js, pmm-app/tests/ia/pages/api/rulesAPI.js, pmm-app/tests/pages/api/settingsAPI.js
Note: changed config for local e2e execution during PR checks. Tests are passing on [CI](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7581/tests)
=> PMM-7776 Verify alerts on email

pmm-app/tests/DbaaS/api/dbaasAPI.js
Temp fix, but only to avoid false positives for release.
=> Avoid False positives due to extra wait time on cluster creation

pmm-app/tests/ia/alertRules_test.js, pmm-app/tests/ia/pages/alertRulesPage.js, pmm-app/tests/ia/pages/api/rulesAPI.js
[tests](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7680/tests) are passing
=> PMM-7818 - updated alert rules tests

.github/workflows/build.yml, .gitignore, pmm-app/src/shared/components/helpers/time-parameters-parser.test.ts, pmm-app/src/shared/components/helpers/time-parameters-parser.ts
Fixes bug related to QAN from/to date parsing in case of invalid value, for example '6h'
=> PMM-7844 fix time parsing in case of wrong period

pmm-app/tests/ia/notificationChannels_test.js, pmm-app/tests/ia/pages/api/channelsAPI.js, pmm-app/tests/ia/pages/api/rulesAPI.js, pmm-app/tests/ia/pages/api/templatesAPI.js, pmm-app/tests/ia/pages/iaCommonPage.js, pmm-app/tests/ia/pages/notificationChannelsPage.js, pmm-app/tests/ia/pagination_test.js
tests are [passing](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7728/tests)
=> PMM-7668 notification channels tests, refactoring

pmm-app/tests/ia/alertRules_test.js, pmm-app/tests/ia/pages/alertRulesPage.js, pmm-app/tests/ia/pages/testData.js
https://jira.percona.com/browse/PMM-7876
tests are [passing](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7855/tests)
=> PMM-7876 alert rules tests, parsing templates

pmm-app/src/pmm-update/UpdatePanel.utils.test.ts, pmm-app/src/pmm-update/UpdatePanel.utils.ts
Fixes incorrect year on update panel
https://github.com/Percona-Lab/pmm-submodules/pull/1678
=> PMM-7825 Fix incorrect year

pmm-app/codeceptConfigHelper.js, pmm-app/linksHelper.js, pmm-app/tests/ia/common_test.js, pmm-app/tests/ia/pages/iaCommonPage.js, pmm-app/tests/pages/api/settingsAPI.js, pmm-app/tests/pages/pmmSettingsPage.js, pmm-app/tests/verifyPMMSettingsPageFunctionality_test.js
tests are [passing](https://pmm.cd.percona.com/blue/organizations/jenkins/pmm2-ui-tests/detail/pmm2-ui-tests/7893/tests)
=> PMM-7890 IA common tests

dashboards/Prometheus_Exporters_Overview.json
=> PMM-7912 Exporters Running Count on Client Instance don't match

dashboards/MySQL_Instance_Summary.json
=> PMM-7991 MySQL Summary panel doesn't exist on MySQL Summary dashboard

pmm-app/src/pmm-update/UpdatePanel.utils.test.ts, pmm-app/src/pmm-update/UpdatePanel.utils.ts
=> Changes from 2.16

dashboards/MySQL_InnoDB_Details.json
=> PMM-5656 InnoDB Checkpoint Age graph not showing max checkpoint age 

dashboards/MongoDB_Instances_Compare.json, dashboards/MongoDB_Instances_Overview.json
=> PMM-8085 Wrong units are used in mongodb memory element

dashboards/MongoDB_ReplSet_Summary.json
=> PMM-7154 Empty elements on MongoDB ReplSet Summary dashboard

dashboards/ProxySQL_Instance_Summary.json
=> PMM-8112 Collect from stats_mysql_commands_counters

dashboards/VictoriaMetrics.json
=> PMM-8220 Victoria Metrics Active Time Series No Changes Report Shows

pmm-app/src/pmm-pt-summary/panel/PTSummary.test.tsx, pmm-app/src/pmm-pt-summary/panel/PTSummary.tsx
https://jira.percona.com/browse/PMM-8405
=> PMM-8405 Fix PTSummary

dashboards/CPU_Utilization_Details.json, dashboards/Node_Summary.json
=> PMM-8584 Issues with CPU metric labels for RDS

dashboards/MongoDB_Cluster_Summary.json
=> PMM-8749 Adding more than 1 mongos breaks pmm mongodb dashboard

pmm-app/src/shared/components/Elements/Charts/TimeDistribution/TimeDistribution.constants.ts
What this PR does / why we need it:
change cpu system time color in TimeDistribution component
Which issue(s) this PR fixes:
https://jira.percona.com/browse/PMM-6763
=> PMM-6763 change cpu system time color

misc/fix-panels.py
=> PMM-7985 Custom Grafana Plugins Installed are not available

pmm-app/package-lock.json, pmm-app/package.json
https://github.com/percona-platform/grafana/pull/242
https://jira.percona.com/browse/PMM-8967
=> PMM-8967 Update grafana version to 7.5.11

dashboards/Experimental/Environment_Summary.json, dashboards/Experimental/Environments_Overview.json, pmm-app/src/plugin.json
[PMM-9356](https://jira.percona.com/browse/PMM-9356) Add two experimental dashboards from [blog](https://www.percona.com/blog/new-experimental-environment-dashboards-for-percona-monitoring-and-management/)
FB: https://github.com/Percona-Lab/pmm-submodules/pull/2242
=> PMM-9356-add-experimental-environment-dashboards-to-pmm

dashboards/MySQL/MySQL_InnoDB_Details.json
[PMM-9372](https://jira.percona.com/browse/PMM-9372) Add availability negative representation on the graph InnoD Buffer Pool LRU Sub-Chain Churn
=> PMM-9372 add available negative representation on the graph

pmm-app/src/shared/components/helpers/api.ts
Fixes API helper types by removing the void return from functions and leaving just the generic type.
https://jira.percona.com/browse/PMM-7031
=> PMM-7031 Fix API helper types

dashboards/PostgreSQL/PostgreSQL_Instances_Overview.json
PMM-9834 Change expression for service counter at Postgresql Overview dashboard.
=> PMM-9834 fix incorrect service counter

dashboards/PostgreSQL/PostgreSQL_Instances_Overview.json
PMM-9834 Change expression for services autovacuum panel at Postgresql Overview dashboard.
=> PMM-9834 fix incorrect services autovacuum panel

.whitesource
This will disable the creation of PRs. We will rely on dependabot.
=> Remove the experimental settings

dashboards/Insight/Home_Dashboard.json
[PMM-9909](https://jira.percona.com/browse/PMM-9909)
Added links to dashboards with node metrics at Home dashboard.
=> PMM-9909 Add links and titles to panels at Home dashboard

dashboards/Experimental/PXC_Galera_Cluster_Summary_Experimental.json
https://jira.percona.com/browse/PMM-9650
=> PMM-9650 fix description and refresh for experemental PXC

dashboards/Experimental/New_Home_Dashboard.json
PMM-10367 Added new experimental home dashboard from DGB.
=> PMM-10367 Experimental home dashboard

dashboards/Experimental/PXC_Galera_Cluster_Summary_Experimental.json
PMM-10300 Some improvements after Marco's review. Change variables list, change hardware panels from gauge to stat, remove queue and query
=> PXC-10030 Improvements at PXC Summary experimental dashboard

dashboards/Experimental/New_Home_Dashboard.json
PMM-10367 
Change link to feedback in disclaimer:
=> PMM-10367 Change link for feedback

dashboards/Experimental/MongoDB_Collection_Details.json, dashboards/Experimental/MongoDB_Collections_Overview.json, dashboards/Experimental/MongoDB_Oplog_Details.json
=> Remove refresh to fix issue with empty cluster

dashboards/Experimental/MongoDB_Collection_Details.json
[PMM-10560](https://jira.percona.com/browse/PMM-10560)
Made this row opened by default. change pmm client to pmm-admin.
=> PMM-10560 Change description for "Connection Activity" row.

dashboards/PostgreSQL/PostgreSQL_Instance_Summary.json, dashboards/PostgreSQL/PostgreSQL_Instances_Compare.json, dashboards/PostgreSQL/PostgreSQL_Instances_Overview.json
[PMM-10624](https://jira.percona.com/browse/PMM-10624)
Removing database with oid 0.
Before
After
=> Add condition datid!="0" to queries for PostgreSQL dashboards.

dashboards/Experimental/PostgreSQL_Vacuum_Monitoring.json
* PMM-10244 Vacuum Monitoring Dashboard
* PMM-10244 Added table bloat queries
* PMM-10244 Added more graphs
* PMM-10244 Changes.
* PMM-10244 Another fix charts.
* PMM-10244 Another fix.
* PMM-10244 New dash.
* PMM-10244 Fix ID and empty line at end of file.
* PMM-10244 Fix datasource.
* PMM-10244 Update name.
* Move to Experimental directory, some changes in panels.
* Added link to forum, increase font size
* Remove Transaction ID Wraparound panel cause high cpu usage.
* trigger
Co-authored-by: Jiří Čtvrtka <62988319+JiriCtvrtka@users.noreply.github.com>
Co-authored-by: Jiří Čtvrtka <jiri.ctvrtka.sde@gmail.com>
Co-authored-by: Anton Bystrov <anton.bystrov@simbirsoft.com>
=> PMM-10244 Vacuum Monitoring Dashboard (#1361)

dashboards/Experimental/PostgreSQL_Vacuum_Monitoring.json
Change panel to full screen width, change query type to "Instant"
=> PMM-10244 Fix panels view

dashboards/Experimental/PostgreSQL_Vacuum_Monitoring.json
Fix some issues at vacuum dashboard.
=> Change panels to full screen width, change Dead Tuples query to Instant

dashboards/Experimental/PostgreSQL_Vacuum_Monitoring.json
https://jira.percona.com/browse/PMM-10751. Move panel to top and hide disclaimer panel.
=> PMM-10751 move service name panel to top

dashboards/MongoDB/MongoDB_Instance_Summary.json, dashboards/MongoDB/MongoDB_ReplSet_Summary.json
PMM-9874 Was changed queries for prevent duplication some data after restart dbaas clusters.
=> PMM-9874 Change queries for MongoDb dashboards

dashboards/Insight/Home_Dashboard.json
PMM-11041 Removed typo previouse - previous at panels
=> PMM-11041 Fix typo in Home Dashboard

dashboards/MySQL/MySQL_InnoDB_Compression_Details.json, dashboards/MySQL/MySQL_InnoDB_Details.json
PMM-11060 Was changed "Innodb" to "InnoDB" in MySQL InnoDB Compression Details and MySQL InnoDB Details dashboards.
=> PMM-11060 Change case "Innodb" to "InnoDB".

dashboards/MySQL/MySQL_User_Details.json
PMM-11313 Added conditions for MariaDB userstats, split query for Users by Rows Fetched/Read.
Splited Rows Fetched/Read panel.
=>  PMM-11313 Added metrics for MariaDB Userstats.

pmm-app/src/pmm-qan/panel/components/Details/Explain/Explain.tools.ts, pmm-app/src/pmm-qan/panel/components/Details/Explain/components/ClassicExplain/ClassicExplain.tsx, pmm-app/src/shared/components/Elements/Table/Table.styles.ts
PMM-9844
Feature Build:
- https://github.com/Percona-Lab/pmm-submodules/pull/3218
=> PMM-9844 Fix details classic explain table view

pmm-app/src/pmm-qan/panel/components/Details/Metrics/Metrics.tsx, pmm-app/src/shared/components/Elements/Charts/Latency/Latency.tsx
PMM-12091
Feature Build:
- https://github.com/Percona-Lab/pmm-submodules/pull/3257
=> PMM-12091 Fix latency tool tips measurement

pmm-app/src/pmm-qan/panel/components/Details/Table/TableContainer.tsx
PMM-10799
Feature Build:
- https://github.com/Percona-Lab/pmm-submodules/pull/3263
=> PMM-10799 Fix error message for table tab

dashboards/Experimental/PXC_Galera_Cluster_Summary_Experimental.json
Fix issues with empty replication latency panels (was deprecated query).
=> PMM-12082 Changed metric name in queries

pmm-app/src/pmm-qan/panel/components/Details/Metadata/Metadata.styles.ts, pmm-app/src/pmm-qan/panel/components/Details/Metadata/Metadata.tsx
[PMM-12229](https://jira.percona.com/browse/PMM-12229)  - Hide metadata table
FB - https://github.com/Percona-Lab/pmm-submodules/pull/3306#issuecomment-1591215699
=> PMM-12229 Hide metadata table

pmm-app/package.json, pmm-app/yarn.lock
Update grafana to 9.2.20 due to CVEs.
PMM-12254
=> PMM-12254 Update to Grafana 9.2.20

pmm-app/src/pmm-qan/panel/components/Details/Metadata/Metadata.styles.ts, pmm-app/src/pmm-qan/panel/components/Details/Metadata/Metadata.tsx
https://jira.percona.com/browse/PMM-6279
=> PMM-6279 Show metadata table again.

dashboards/MongoDB/MongoDB_Cluster_Summary.json
=> PMM-12263 Fix replication lag of PSA RS in MongoDB_Cluster_Summary.json

dashboards/Experimental/Environments_Overview.json, dashboards/Insight/Home_Dashboard.json
https://github.com/Percona-Lab/pmm-submodules/pull/3338
=> PMM-12280 make the Service Summary collapsed by default

dashboards/OS/Node_Summary.json
[PMM-12281](https://jira.percona.com/browse/PMM-12281)
FB - https://github.com/Percona-Lab/pmm-submodules/pull/3326#issuecomment-1619998809
Before - 
After -
=> PMM-12070 Add Table plugin - node summary

pmm-app/src/pmm-qan/panel/components/Details/database-models/mysql/mysql.utils.ts
PMM-12328
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3329
=> PMM-12328 Use query id even when example is available

dashboards/OS/Nodes_Overview.json
[PMM-12282](https://jira.percona.com/browse/PMM-12282)
FB - https://github.com/Percona-Lab/pmm-submodules/pull/3328#issuecomment-1653045468
Before - 
After -
=> PMM-12070 Add table plugin node overview dashboard

dashboards/Kubernetes (experimental)/Kubernetes_DB_Cluster.json
* PMM-12866 update k8s db cluster dashboard
=> PMM-12866 fix k8s db cluster dashboard (#1561)

pmm-app/package.json, pmm-app/yarn.lock
Fixes the yarn test command for the following error:
```
Error [ERR_REQUIRE_ESM]: require() of ES Module
```
=> PMM-7 Fix yarn test command

dashboards/Insight/Home_Dashboard.json, dashboards/OS/Nodes_Overview.json
PMM-12948
Database uptime reported is wrong in PMM.
=> PMM-12948   Database uptime reported is wrong in PMM.

dashboards/Experimental/PMM Health 2-1713168613036.json
https://perconadev.atlassian.net/browse/PMM-3303
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3607
=> PMM-3303-monitor-clickhouse

.github/workflows/build.yml
Cherry pick of 9d392a8ee7dfe5609b48d160e085f460ee1b57c2 from main (#1600)
=> PMM-7 Run test pipeline on every PR

dashboards/Experimental/MongoDB_Cluster_Summary_(new).json, dashboards/Experimental/MongoDB_ReplSet_Summary_(New).json
https://perconadev.atlassian.net/browse/PMM-12753
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3614#issuecomment-2060705310
=> PMM-12753 Add new Mongodb cluster dashboard

dashboards/Experimental/MongoDB_Cluster_Summary_(new).json, dashboards/Experimental/MongoDB_ReplSet_Summary_(New).json
* PMM-12753 Add new Mongodb cluster dashboard
* PMM-12753 Add mongodb replset summary dashboard
---------
=> PMM-12753 Add new Mongodb cluster dashboard (#1592)

dashboards/Experimental/MongoDB_Cluster_Summary_(new).json, dashboards/Experimental/MongoDB_ReplSet_Summary_(New).json
[PMM-13227](https://perconadev.atlassian.net/browse/PMM-13227)
[PMM-13217](https://perconadev.atlassian.net/browse/PMM-13217)
[PMM-13227]: https://perconadev.atlassian.net/browse/PMM-13227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PMM-13217]: https://perconadev.atlassian.net/browse/PMM-13217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-13217 Show mongos version and rename the dashboard

dashboards/Experimental/MongoDB_Cluster_Summary_(new).json, dashboards/Experimental/MongoDB_Collections_Overview.json, dashboards/Experimental/MongoDB_Oplog_Details.json
[PMM-13029](https://perconadev.atlassian.net/browse/PMM-13029)
[PMM-13257](https://perconadev.atlassian.net/browse/PMM-13257)
[PMM-13029]: https://perconadev.atlassian.net/browse/PMM-13029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PMM-13257]: https://perconadev.atlassian.net/browse/PMM-13257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-13257 Cleanup dashboards

dashboards/MongoDB/MongoDB_ReplSet_Summary.json
[PMM-13356](https://perconadev.atlassian.net/browse/PMM-13356)
[PMM-13356]: https://perconadev.atlassian.net/browse/PMM-13356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-13356 Fix variables

dashboards/MongoDB/MongoDB_ReplSet_Summary.json
* PMM-13356 Fix variables
* PMM-13356 Fix according to PMM-9403
=> PMM-13356 Fix variables (#1632)

dashboards/MongoDB/MongoDB_Oplog_Details.json
[PMM-13486](https://perconadev.atlassian.net/browse/PMM-13486)
[PMM-13486]: https://perconadev.atlassian.net/browse/PMM-13486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-13486 Add new metrics for Mongodb 8

dashboards/MongoDB/MongoDB_Router_Summary.json
[PMM-13681](https://perconadev.atlassian.net/browse/PMM-13681)
[PMM-13681]: https://perconadev.atlassian.net/browse/PMM-13681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-13681 Remove tag and disclaimer

pmm-app/src/pmm-qan/panel/QueryAnalytics.constants.ts
PMM-12468
Percona Toolkit PR: https://github.com/percona/percona-toolkit/pull/920
PMM PR: https://github.com/percona/pmm/pull/3496
FB: https://github.com/Percona-Lab/pmm-submodules/pull/3832
=> PMM-12468 Add full scan to MongoDB.

dashboards/MongoDB/MongoDB_Cluster_Summary.json
[PMM-12161](https://jira.percona.com/browse/PMM-12161)
[PMM-12161]: https://perconadev.atlassian.net/browse/PMM-12161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-12161 Add shard topology

dashboards/Experimental/Environments_Overview.json, dashboards/Insight/Home_Dashboard.json, dashboards/Insight/Prometheus_Exporter_Status.json
[PMM-13770](https://perconadev.atlassian.net/browse/PMM-13770)
[PMM-13770]: https://perconadev.atlassian.net/browse/PMM-13770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-13770 Remove agent_id from queries

.github/CODEOWNERS
Cherry pick of 4e6b5dc91e3441ee35baee60f9d046841aa5a929 (#1661)
=> PMM-7 Update CODEOWNERS

dashboards/PostgreSQL/PostgreSQL_Checkpoints_Buffers_WAL_Usage.json, pmm-app/src/plugin.json
[PMM-13864](https://perconadev.atlassian.net/browse/PMM-13864)
[PMM-13864]: https://perconadev.atlassian.net/browse/PMM-13864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-13864 Add PG checkpoints wal buffers dashboard

dashboards/PostgreSQL/PostgreSQL_Replication_Overview.json
[PMM-13866](https://perconadev.atlassian.net/browse/PMM-13866)
[PMM-13866]: https://perconadev.atlassian.net/browse/PMM-13866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PMM-13866 Add pg replication dashboard

dashboards/MongoDB/MongoDB_Collections_Overview.json
Fixed the chart expression to match the values in the variable
Reviewers: @percona/pmm-review-fe
=> PMM-14070 fix expression on chart Top 5 Databases By Size v2

dashboards/MongoDB/MongoDB_WiredTiger_Details.json
WT tickets dashboard was not rendering properly the read vs write tickets
=> fix tw tickets panel
